// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbOlAoXWbgcCZSlOk5zrCItbOLVIoe5JM',
    appId: '1:944670323779:web:433d60ed4cd6a6334390f6',
    messagingSenderId: '944670323779',
    projectId: 'dietrao-418d5',
    authDomain: 'dietrao-418d5.firebaseapp.com',
    storageBucket: 'dietrao-418d5.firebasestorage.app',
    measurementId: 'G-0P6QBSBENM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPErpQqMqDC9ZJcoww2iw8bBvRISh2BVM',
    appId: '1:944670323779:android:e2c4fc2e74c85b2e4390f6',
    messagingSenderId: '944670323779',
    projectId: 'dietrao-418d5',
    storageBucket: 'dietrao-418d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy7larj4XoQ3nZ22-8b4LP6bDOTwq_U2s',
    appId: '1:944670323779:ios:b5f09c20fc5385134390f6',
    messagingSenderId: '944670323779',
    projectId: 'dietrao-418d5',
    storageBucket: 'dietrao-418d5.firebasestorage.app',
    androidClientId: '944670323779-mfrvaq9tmfj4ucsfgs6hjt0tdp6h5qmc.apps.googleusercontent.com',
    iosClientId: '944670323779-0kvu9n4t53d4v7tus56e77f8lp8seju1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy7larj4XoQ3nZ22-8b4LP6bDOTwq_U2s',
    appId: '1:944670323779:ios:b5f09c20fc5385134390f6',
    messagingSenderId: '944670323779',
    projectId: 'dietrao-418d5',
    storageBucket: 'dietrao-418d5.firebasestorage.app',
    androidClientId: '944670323779-mfrvaq9tmfj4ucsfgs6hjt0tdp6h5qmc.apps.googleusercontent.com',
    iosClientId: '944670323779-0kvu9n4t53d4v7tus56e77f8lp8seju1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbOlAoXWbgcCZSlOk5zrCItbOLVIoe5JM',
    appId: '1:944670323779:web:9ae8d8c3936b0e324390f6',
    messagingSenderId: '944670323779',
    projectId: 'dietrao-418d5',
    authDomain: 'dietrao-418d5.firebaseapp.com',
    storageBucket: 'dietrao-418d5.firebasestorage.app',
    measurementId: 'G-ZYL25V3X47',
  );
}
